"""modify users table

Revision ID: 7478137d0baf
Revises: 4b748a1eea6a
Create Date: 2023-11-03 02:36:03.660407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7478137d0baf'
down_revision = '4b748a1eea6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=True))
        batch_op.drop_column('school_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('school')

    # ### end Alembic commands ###
